version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_PORT=5432
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - "./data/postgres_data:/var/lib/postgresql/data"