apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-frontend
  template:
    metadata:
      labels:
        app: movies-frontend
    spec:
      containers:
      - name: movies-frontend
        image: emilkarlstrombth/movies_service_frontend:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: movies-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: movies-frontend-balancer
spec:
  type: LoadBalancer
  selector:
    app: movies-frontend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
