apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-api-config
data:
  DB_HOST: "NOTSET"
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-frontend-config
data:
  API_URI: "NOTSET"
  API_PORT: "4000"