apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-api-config
data:
  DB_HOST: "NOTSET"
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movies-frontend-config
data:
  API_URI: "NOTSET"
  API_PORT: "4000"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "pass"
# It's kind of annoying but I couldn't get Secrets to mix with ConfigMaps so 
# I'll just put this here. Not really sure why but I got undefined characters
# when I read them in from the database