apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies-service
  template:
    metadata:
      labels:
        app: movies-service
    spec:
      containers:
      - name: movies-service
        image: emilkarlstrombth/movies_service_backend:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        envFrom:
          - configMapRef:
              name: movies-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: movies-service-balancer
spec:
  type: LoadBalancer
  selector:
    app: movies-service
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
