apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: pass
  POSTGRES_DB: database
immutable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image:  postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_DB
          volumeMounts:
            - mountPath: var/lib/postgresql/data 
              name: postgredb
      volumes:  
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim 